### PR TITLE
Updated trash-cli from 1.4.0 to 3.0.0 

### PR DESCRIPTION
**Pull request by taha437**
## Description

build(package.json): Bumped trash-cli from 1.4.0 to 3.0.0 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by taha437** [comment]
@artalat kindly review this

**Comment by artalat** [comment]
Why do we need this package? Where is it used?

**Comment by taha437** [comment]
> Why do we need this package? Where is it used?

Its only included in package.json. We aren't using it anywhere. Should i delete it?

**Comment by artalat** [comment]
Yes please.

**Comment by taha437** [comment]
> Yes please.

Removed!

**Pull request merged**
