### PR TITLE
Updated react-test-renderer from 16.8.6 to 16.9.0

### PR DESCRIPTION
**Pull request by taha437**
## Description

 build(package.json): Bumped react-test-renderer from 16.8.6 to 16.9.0

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by taha437** [comment]
@artalat kindly review this

**Comment by artalat** [comment]
are we using this?

**Comment by taha437** [comment]
> are we using this?

Yes, we are using Test Renderer from this library in testing of components.

**Pull request merged**
