### PR TITLE
Updated react-native from 0.59.8 to 0.60.5

### PR DESCRIPTION
**Pull request by taha437**
## Description

build(package.json): Bumped react-native from 0.59.8 to 0.60.5

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by taha437** [comment]
@artalat kindly review this

**Comment by artalat** [comment]
How did you test it

**Comment by taha437** [comment]
> How did you test it

Ran the command 'yarn test'. It exited successfully.

**Comment by artalat** [comment]
you need to run storybook native and test it

**Pull request merged**
